development:
  adapter: postgresql
  encoding: unicode
  database: mt
  pool: 5
  username: postgres
  password: backdraft
  host: 188.166.167.206
  port: 5432




production:
  adapter: postgresql
  encoding: unicode
  database: mt
  pool: 5
  username: postgres
  password: backdraft
  host: 188.166.167.206
  port: 5432
